name: storefront

type: 'nodejs:10'

build:
    flavor: none

variables:
    env:
        # NODE_OPTIONS: --max-old-space-size=768
        NO_UPDATE_NOTIFIER: true

hooks:
    build: !include
        type: string
        path: upstreams/storefront.sh
    # post_deploy: |
    #     cd saleor-storefront
    #     echo $API_URI
    #     ls -a
    #     npm run build

# The size of the persistent disk of the application (in MB).
disk: 1024

# mounts:
#     saleor-storefront/dist:
#         source: local
#         source_path: dist
#     saleor-storefront/.next:
#         source: local
#         source_path: 'next'

web:
    locations:
        '/':
            # The public directory of the application relative to its root.
            root: 'saleor-storefront/dist'
            index: ['index.html']
            scripts: false
            allow: true
            expires: 1d